# GENERATED FILE

# Constant definitions for pretty printers.
# See gen-py-const.awk for details.

PTHREAD_MUTEX_KIND_MASK = 3
PTHREAD_MUTEX_NORMAL = 0
PTHREAD_MUTEX_RECURSIVE = 1
PTHREAD_MUTEX_ERRORCHECK = 2
PTHREAD_MUTEX_ADAPTIVE_NP = 3
PTHREAD_MUTEX_DESTROYED = -1
PTHREAD_MUTEX_UNLOCKED = 0
PTHREAD_MUTEX_LOCKED_NO_WAITERS = 1
PTHREAD_MUTEX_INCONSISTENT = 2147483647
PTHREAD_MUTEX_NOTRECOVERABLE = 2147483646
FUTEX_OWNER_DIED = 1073741824
FUTEX_WAITERS = -2147483648
FUTEX_TID_MASK = 1073741823
PTHREAD_MUTEX_ROBUST_NORMAL_NP = 16
PTHREAD_MUTEX_PRIO_INHERIT_NP = 32
PTHREAD_MUTEX_PRIO_PROTECT_NP = 64
PTHREAD_MUTEX_PSHARED_BIT = 128
PTHREAD_MUTEX_PRIO_CEILING_SHIFT = 19
PTHREAD_MUTEX_PRIO_CEILING_MASK = -524288
PTHREAD_MUTEXATTR_PROTOCOL_SHIFT = 28
PTHREAD_MUTEXATTR_PROTOCOL_MASK = 805306368
PTHREAD_MUTEXATTR_PRIO_CEILING_MASK = 16773120
PTHREAD_MUTEXATTR_FLAG_ROBUST = 1073741824
PTHREAD_MUTEXATTR_FLAG_PSHARED = -2147483648
PTHREAD_MUTEXATTR_FLAG_BITS = -251662336
PTHREAD_MUTEX_NO_ELISION_NP = 512
PTHREAD_PRIO_NONE = 0
PTHREAD_PRIO_INHERIT = 1
PTHREAD_PRIO_PROTECT = 2
PTHREAD_COND_SHARED_MASK = 1
PTHREAD_COND_CLOCK_MONOTONIC_MASK = 2
COND_CLOCK_BITS = 1
PTHREAD_COND_WREFS_SHIFT = 3
PTHREAD_RWLOCK_PREFER_READER_NP = 0
PTHREAD_RWLOCK_PREFER_WRITER_NP = 1
PTHREAD_RWLOCK_PREFER_WRITER_NONRECURSIVE_NP = 2
PTHREAD_RWLOCK_WRPHASE = 1
PTHREAD_RWLOCK_WRLOCKED = 2
PTHREAD_RWLOCK_READER_SHIFT = 3
PTHREAD_PROCESS_PRIVATE = 0
PTHREAD_PROCESS_SHARED = 1
